# site properties and page defaults
title: Neural dynamics, Control & Learning Lab
subtitle: — NeCoLe Lab —
description: We study neural dynamics.
header: images/background.png
footer: images/background.png
proofer: false

# site social media and other links
links:
  email: laureline.logiaco@cuanschutz.edu
  orcid: 0000-0001-5252-7662
  google-scholar: NFQh44IAAAAJ
  github: LaurelineLogiaco
  #twitter: LaurelineLogiaco
  #youtube: LaurelineLogiaco

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member

  - scope:
      type: "researchdirections"
    values:
      layout: member

  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
