- id: doi:10.1016/j.celrep.2021.109090
  type: paper
  description:
  date: 2021-06-1
  image: https://www.cell.com/cms/10.1016/j.celrep.2021.109090/asset/b4799bbf-b66c-4402-bd73-55b7e18222c6/main.assets/fx1_lrg.jpg
  buttons:
  tags:
  repo:


- id: doi:10.1111/ejn.16553
  type: paper
  description:
  date: 2024-10-04
  image: https://onlinelibrary.wiley.com/cms/asset/f556751e-b642-4d16-b696-c85fc6c61832/ejn16553-toc-0001-m.jpg
  buttons:
  tags:
  repo:

- id:
  type: book
  description:
  date: 2023-12-01
  image: https://oup.silverchair-cdn.com/oup/backfile/content_public/books/55212/parts/med-9780197676158-chapter-34/1/s_med-9780197676158-graphic-125.jpeg?Expires=2147483647&Signature=tEc-lryfiyiY7RqrKeg7fgyMbl6ATTDFUoYPK3qoWkDVEB-8DzJUmMS4f46qsTNl5QBhdTrEu17S9c1sCjkrb~F~tEgSjD9iYpbAwkx6xpplW~xAfMWKjIJvgY731FCDN6btnXbyn27R14xS0IhXsBz-~cCWF2q3DdHKmtEHHZtFj8gqZWBI4e52x7b4BsmDHDxzyB46Ct84RCSfUBHbIQGl6OS2wZ5HGxSaTD3tH9p7KDfcNhBVDVR1ta002mmJGZWxYwzpDlPtCHEzbapJLHV-FcnQ~pyhkwoOboECiYlbbIEuVpsdSi~A0KCFkgp8YZG~FZffQzgXg30MXOKqTQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  buttons:
  tags:
  repo:
  
#- id: doi:10.1371/journal.pcbi.1007128
#  type: paper
#  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#  date: 2020-12-4
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  buttons:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open science
#    - collaboration
#  repo: greenelab/meta-review
