- id: doi:10.1016/j.celrep.2021.109090
  type: paper
  description:
  date: 2021-06-1
  image: images/graphicalAbstract_Logiaco2021.jpg
  buttons:
  tags:
  repo:


- id: doi:10.1111/ejn.16553
  type: paper
  description:
  date: 2024-10-04
  image: https://onlinelibrary.wiley.com/cms/asset/f556751e-b642-4d16-b696-c85fc6c61832/ejn16553-toc-0001-m.jpg
  buttons:
  tags:
  repo:

- id: doi:10.1093/med/9780197676158.003.0034
  type: book
  description:
  date: 2023-12-01
  image: images/chapterGraph.png
  buttons:
  tags:
  repo:

- id: doi:10.12751/NNCN.BC2023.264
  type: conf_abstract
  description:
  date: 2023-09-18
  image: images/dualCntrl_proj1_v2.png
  buttons:
  tags:
  repo:

- id: doi:10.3389/fnsyn.2020.585539
  type: paper
  description:
  date: 2020-11-02
  image: https://www.frontiersin.org/files/Articles/585539/fnsyn-12-585539-HTML-r2/image_m/fnsyn-12-585539-g001.jpg
  buttons:
  tags:
  repo:

- id: doi:10.1101/2019.12.17.880153
  type: preprint
  description:
  date: 2019-12-18
  image: https://www.biorxiv.org/content/biorxiv/early/2019/12/18/2019.12.17.880153/F1.medium.gif
  buttons:
  tags:
  repo:

- id: pmid:26266537
  type: paper
  description:
  date: 2015-08-12
  image: https://journals.plos.org/plosbiology/article/figure/image?size=large&id=10.1371/journal.pbio.1002222.g002
  buttons:
  tags:
  repo:

- id: arXiv:2006.13332
  type: preprint
  description:
  date: 2020-06-23
  image: images/ML_draft_thalamocortical.png
  buttons:
  tags:
  repo:
  
#- id: doi:10.1371/journal.pcbi.1007128
#  type: paper
#  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#  date: 2020-12-4
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  buttons:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open science
#    - collaboration
#  repo: greenelab/meta-review
