- id: doi:10.1016/j.celrep.2021.109090
  type: paper
  description:
  date: 2021-06-1
  image: https://www.cell.com/cms/10.1016/j.celrep.2021.109090/asset/b4799bbf-b66c-4402-bd73-55b7e18222c6/main.assets/fx1_lrg.jpg
  buttons:
  tags:
  repo:


- id: doi:10.1111/ejn.16553
  type: paper
  description:
  date: 2024-10-04
  image: https://onlinelibrary.wiley.com/cms/asset/f556751e-b642-4d16-b696-c85fc6c61832/ejn16553-toc-0001-m.jpg
  buttons:
  tags:
  repo:

- id: doi:10.1093/med/9780197676158.003.0034
  type: book
  description:
  date: 2023-12-01
  image: https://oup.silverchair-cdn.com/oup/backfile/content_public/books/55212/parts/med-9780197676158-chapter-34/1/s_med-9780197676158-graphic-125.jpeg?Expires=2147483647&Signature=tEc-lryfiyiY7RqrKeg7fgyMbl6ATTDFUoYPK3qoWkDVEB-8DzJUmMS4f46qsTNl5QBhdTrEu17S9c1sCjkrb~F~tEgSjD9iYpbAwkx6xpplW~xAfMWKjIJvgY731FCDN6btnXbyn27R14xS0IhXsBz-~cCWF2q3DdHKmtEHHZtFj8gqZWBI4e52x7b4BsmDHDxzyB46Ct84RCSfUBHbIQGl6OS2wZ5HGxSaTD3tH9p7KDfcNhBVDVR1ta002mmJGZWxYwzpDlPtCHEzbapJLHV-FcnQ~pyhkwoOboECiYlbbIEuVpsdSi~A0KCFkgp8YZG~FZffQzgXg30MXOKqTQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  buttons:
  tags:
  repo:

- id: doi:10.12751/NNCN.BC2023.264
  type: conf_abstract
  description:
  date: 2023-09-18
  image: https://laurelinelogiaco.github.io/lab_compneuroCUAnschutz/images/general_multiRegionNN_brain_schematic.png
  buttons:
  tags:
  repo:

- id: doi:10.3389/fnsyn.2020.585539
  type: paper
  description:
  date: 2020-11-02
  image: https://www.frontiersin.org/files/Articles/585539/fnsyn-12-585539-HTML-r2/image_m/fnsyn-12-585539-g001.jpg
  buttons:
  tags:
  repo:

- id: doi:10.1101/2019.12.17.880153
  type: preprint
  description:
  date: 2019-12-18
  image: https://www.biorxiv.org/content/biorxiv/early/2019/12/18/2019.12.17.880153/F1.medium.gif
  buttons:
  tags:
  repo:

 -id: doi:10.1371/journal.pbio.1002222
  type: paper
  description:
  date: 2015-08-12
  image: https://storage.googleapis.com/plos-corpus-prod/10.1371/journal.pbio.1002222/1/pbio.1002222.g002.PNG_I?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=wombat-sa%40plos-prod.iam.gserviceaccount.com%2F20250716%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20250716T191542Z&X-Goog-Expires=86400&X-Goog-SignedHeaders=host&X-Goog-Signature=9c7384acd18cab3386178ff9745790eb678d7cbf25cfaf67730428f1766eba8113a15d649c2f93d7fb142627674d305b071081a7c2866856b14c5393ea34b685864a21b10e2915a9ffd659f0956c4127090470d73800cd1dc2a39bdfc1ae10e861b4083a095452c25c4936c2dd4553e50accf7f1ac454c6db74a4f5065fc530ccfc0a9d6256a103a29d83e687a6db1276f21517d30bdd8650e2e498d5108739713b2e2e736ecc0ff0a59c29a8767281190a993dfee667c4deb5d44437991832341dbc8b27e9e3f286358302e9291958d5eb2c07fbb84c64774db7c3ac34b464416fa6219dfc09bae24128c12493ae6f808548d28ffcba6cafedd399d097aab94
  buttons:
  tags:
  repo:
  
#- id: doi:10.1371/journal.pcbi.1007128
#  type: paper
#  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#  date: 2020-12-4
#  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#  buttons:
#    - type: manubot
#      link: https://greenelab.github.io/meta-review/
#    - type: source
#      text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#      link: http://manubot.org/
#  tags:
#    - open science
#    - collaboration
#  repo: greenelab/meta-review
